List<String> getLyrics() {
  return [
    'Tengo recuerdos en mi corazón',
    'Tantos que me hacen perder la razón',
    'Imaginando que estás conmigo',
    'Esa es mi mayor ilusión.',
    '',
    'Si las cosas ya pasaron no importa cariño',
    'Porque serás mi recuerdo que jamás olvido',
    'Sentimientos que pasan, pero no consigo',
    'Pero no consigo quitar lo que siente',
    'Este tonto corazón que te lleva presente',
    'Y aunque no creas, sigue igual de fuerte.',
    '',
    'Ya pasaron unos años',
    'Cuántas cosas han cambiado',
    'Mis sentimientos no',
    'Pero creo que he encontrado',
    'La forma de seguir',
    'Sin tenerte a mi lado',
    'La forma de seguir',
    'Y el hecho haberlo aceptado',
    'Pero te sueño',
    'Y algo siento',
    'despierto',
    'Me desconcierto',
    'Pero es cierto',
    'No te miento',
    'No sé inventan',
    'Sentimientos',
    'Intenté mostrarlo',
    'Con el paso del tiempo',
    'Y no pude convencerte',
    'Que es sincero lo que siento',
    '',
    'Si las cosas ya pasaron no importa cariño',
    'Porque serás mi recuerdo que jamás olvido',
    'Sentimientos que pasan, pero no consigo …',
    '(Yo no lo consigo)',
    'Pero no consigo quitar lo que siente',
    'Este tonto corazón que te lleva presente',
    'Y aunque no creas, sigue igual de fuerte.',
    '(Igual de fuerte)',
    '',
    'Jamás sentí algo parecido',
    'Y nunca te mentí',
    'Eras mi sueño, mi alegría',
    'Y era por ti',
    'Todo lo que hacía',
    'Lo hacía por ti',
    '(Lo hacía por ti)',
    'Y es así',
    'Se que tuve errores',
    'Y me arrepentí',
    'Las cosas no salieron',
    'Y pues que decir',
    'Ahora solo nos queda',
    'Seguir y vivir',
    '(Seguir y vivir)',
    '',
    '',
    'Y bueno ahora son recuerdos',
    'El parque, la alameda',
    'Nuestro punto de encuentro',
    'Las estrellas, tu mirada,',
    'Y ese primer beso',
    'Fueron los ingredientes',
    'Del momento perfecto',
    'Después vino el panda',
    'Y un tiempo de silencio',
    'Tiempo de confusión',
    'Que acabaría con el cuento',
    'Pero ni yo entiendo',
    'Porque guardo una esperanza',
    'Si está claro la postura',
    'Cada quién para su casa',
    '',
    '',
    'Si las cosas ya pasaron no importa cariño',
    'Porque serás mi recuerdo que jamás olvido',
    'Sentimientos que pasan, pero no consigo …',
    '(Yo no lo consigo)',
    'Pero no consigo quitar lo que siente',
    'Este tonto corazón que te lleva presente',
    'Y aunque no creas, sigue igual de fuerte.',
    '(Igual de fuerte)',
    '',
    'Jamás sentí algo parecido',
    'Y nunca te mentí',
    'Eras mi sueño, mi alegría',
    'Y era por ti',
    'Todo lo que hacía',
    'Lo hacía por ti',
    '(Lo hacía por ti - Jared)',
    'Y es así',
    'Sé que tuve errores',
    'Y me arrepentí',
    'Las cosas no salieron',
    'Y pues que decir',
    'Ahora solo nos queda',
    'Seguir y vivir',
    '',
    '(Seguir y vivir)'
  ];
}
